# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Computaria - assuntos computacionais por Jefferson Quesado
email: jeff.quesado@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Devaneios e dicas de programação e outros demais assuntos, relacionados
  à programação, computação ou engenharia de software.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://computaria.gitlab.io" # the base hostname & protocol for your site
twitter_username: JeffQuesado
github_username:  jeffque
gitlab_username:  jefferson.quesado
stackoverflow_username: jefferson-quesado
stackoverflow_userid: 64969

repository:
  base: "https://gitlab.com/computaria/blog/"
  blob_root: "https://gitlab.com/computaria/blog/-/blob/master/"
  tree_root: "https://gitlab.com/computaria/blog/-/tree/master/"

plugins:
  - jekyll-katex

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md", "bin/", "Makefile", "Rakefile", ".env", ".env.example"]
